name: foodster
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+6

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  get: ^4.6.1
  persistent_bottom_nav_bar: ^4.0.2
  carousel_slider: ^4.0.0
  google_maps_flutter: ^2.1.1
  # geolocator: ^8.2.0
  flutter_svg: ^1.0.3
  firebase_core: ^1.12.0
  firebase_database: ^9.0.6
  intl: ^0.17.0
  shared_preferences: ^2.0.12
  cached_network_image: ^3.2.0
  flutter_spinkit: ^5.1.0
  sqflite: ^2.0.2
  url_launcher: ^6.0.18
  share_plus: ^3.0.4
  flutter_local_notifications: ^9.3.2
  timezone: ^0.8.0
  zoom_widget: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true


  assets:
      - assets/images/
      - assets/svg/

  fonts:
      - family: rubik_light
        fonts:
          - asset: assets/fonts/rubik_light.ttf
      - family: rubik_regular
        fonts:
          - asset: assets/fonts/rubik_regular.ttf
